'Joseph Wong': 
  position: 'President'
  email: 'wongzee@pacific.net.sg'
  intro: "Badminton turned squash player during NS days in the early '80s. Been playing for the past 20 years, first with Ulu Pandan Squash team and then Mariner Pioneers. Retired in '99 due to injury. Last grade was B. One of UCSC's pioneers. Squash is appealing because of its discipline and commitment in order to excel in it. A productive way of keeping fit in a short space of time."

'Michael CS Tan':
  position: 'Vice President'
  email: 'MT15@ntrs.com'
  intro: "Sometimes banker, full-time squash fanatic! Dedicated to converting Singapore Sports officials into fellow supporters of a truly phenomenal global sport, and to set medal expectations aside."

'Daryle Teng':
  email: 'coloris_dt@hotmail.com'
  intro: "After 8-9 years away from squash since 1988-96, I finally came back to play after meeting a new bunch of squash enthusiats namely Joseph, Kelvin, Alfred and Andrew in the Intercon tournament.But what make me continue to play is the friendly,caring and enthusiam shown by members of OUR CLUB to promote not only squash but friendship among the sporting arena. From the formation years of UCSC and my subsequent appointment as Disciplinary Chairman, till now I am glad to announce that todate no disciplinary action has been taken against any club members. I am proud of this record not because of the existence of this post but proud of our fellow members self-discipline which made this post seem rather unnecessary. '..... ...CARING for our fellow members in every aspect of our game and life is the best discipline I hope we can achieve .............'"

'Bobby Pang':
  email: 'pangbobby@gmail.com'
  intro: "I was first married to badminton for many years in the 80s and then in recent years found myself having an affair with squash after I stumbled into this UCSC website. Keeping this affair going is no easy task as it demands total dedication and requires plenty of sacrifices. Occasionally things do get out of hand and I will suffer from aches all over my body when that happens. On the positive side my waistline has been shrinking since the affair started. That's why this whole affair thing is so exciting to me in the first place. Come on down and join us to - 'SHED YEARS FROM YOUR AGE AND ADD YEARS TO YOUR LIFE'."

'Dave Phua':
  email: 'hanmar@pacific.net.sg'
  intro: "I started playing squash during the 70's. The love of the game continues to grow with me and my family. Through squash, I have made many good friends. As a result of such interaction the idea of forming UCSC was started and eventually bore fruit. My next commitment to the game is to see my two sons Marcus and Hansel playing a high level of squash and building UCSC into the most popular squash club in Singapore."

'Linda Tan':
  position: 'Treasurer'
  email: 'lyntan49@yahoo.com.sg'
  intro: "Became a squash enthusiast in the early ‘80s. Stopped playing when the squash centres closed down one by one in the late ‘80s and my ‘kakis’ turned to golf. I introduced the game to my boys 3 years ago and was delighted when I chanced upon the UCSC group at Yio Chu Kang in 2006. We’ve been playing regularly ever since, made many new friends and are extremely glad to be a part of this fantastic family."

'Kelvin Kan': 
  email: 'kpl_kan@yahoo.com.sg'
  intro: "Started playing squash after moving into Orchid Park in 1994 mainly to get some fitness for my first love in soccer! Never in my wildest dreams that after playing socially with fellow residents and subsequently helped to form UCSC with the Bishan Park squash 'die-hards', this game and the club has given me an opportunity to meet some really nice and friendly people! Absolutely no regrets and urge any squash beginners and/or enthusiasts to 'look no further' than UCSC!!"

'Bryan Tan':
  email: 'bryan_tan@gmail.com'
  intro: ''

'Boa Ho Man':
  email: 'boa.homan@gmail.com'
  position: 'Webmaster'
  intro: 'Webmaster'

'Mabel Low':
  email: 'mabel_lowsf@hotmail.com'
  intro: 'Chubs'

'Darryl Tan':
  email: 'darryltan@gmail.com'
  intro: "Hello! My name is Darryl Tan. I joined UCSC in 2008, together with my family. Since then, I have fully enjoyed my days in this amazing club. As a training ground for good proper squash, UCSC offered me an enormous variety of players to spar with. Week after week, I would be challenged with new players and new playing styles to counter. It is through the numerous social games that I have grown as both a sportsman and person in so many ways. Having said that, outside the courts, UCSC is more than just a club to me. It is also my second home. After games, it is not uncommon to find members mingling with each other while waiting for their next game - and without saying, I am no different. Personally, I feel that the club's friendly and warm culture is what fills me with happiness to be there. The friendships I have fostered are truly valuable, old and new alike. If there is one place I'd go for challenging games and a relaxing time over tea break afterwards, you know where I will be."
